### ISSUE TITLE
Inference Code

### ISSUE THREAD

**Issue by deepakbandela** [manikanthp/LayoutLMV3_Fine_Tuning#1]
Hi Manikanth,

It has been very good to see your code working out of the box. Many viewers have asked for the inference code from this piece. 

Can you please expedite the inference code for this repository?

Thanks
Deepak

**Comment by deepakbandela** [comment]
Thanks for sharing the inference code. I'm getting this error while running your code using python 3.9 and following requrements.


tqdm~=4.66.1
PyMuPDF~=1.20.2
#paddleocr~=2.6.0
paddleocr~=2.7.0.3
paddlepaddle~=2.5.1
Pillow~=10.0.0
numpy~=1.24.4
torch~=2.0.1
transformers~=4.33.1
pytesseract~=0.3.10
pyyaml~=6.0.1
envyaml~=1.10.211231
python-dateutil~=2.8.2
img2pdf~=0.4.4
boto3~=1.28.55
python-dotenv~=1.0.0


Traceback (most recent call last):
  File "/home/ai/work/code/LayoutLMV3_Fine_Tuning-main/venv/lib/python3.9/site-packages/transformers/models/layoutlmv3/modeling_layoutlmv3.py", line 266, in calculate_spatial_position_embeddings
    right_position_embeddings = self.x_position_embeddings(bbox[:, :, 2])
  File "/home/ai/work/code/LayoutLMV3_Fine_Tuning-main/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ai/work/code/LayoutLMV3_Fine_Tuning-main/venv/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home/ai/work/code/LayoutLMV3_Fine_Tuning-main/venv/lib/python3.9/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ai/work/code/LayoutLMV3_Fine_Tuning-main/src/Inference.py", line 51, in <module>
    op = model(input_ids = inputs_ids.unsqueeze(0), 
  File "/home/ai/work/code/LayoutLMV3_Fine_Tuning-main/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ai/work/code/LayoutLMV3_Fine_Tuning-main/src/trainer.py", line 24, in forward
    output = self.model(input_ids,attention_mask=attention_mask,bbox=bbox,pixel_values=pixel_values)
  File "/home/ai/work/code/LayoutLMV3_Fine_Tuning-main/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ai/work/code/LayoutLMV3_Fine_Tuning-main/venv/lib/python3.9/site-packages/transformers/models/layoutlmv3/modeling_layoutlmv3.py", line 1103, in forward
    outputs = self.layoutlmv3(
  File "/home/ai/work/code/LayoutLMV3_Fine_Tuning-main/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ai/work/code/LayoutLMV3_Fine_Tuning-main/venv/lib/python3.9/site-packages/transformers/models/layoutlmv3/modeling_layoutlmv3.py", line 912, in forward
    embedding_output = self.embeddings(
  File "/home/ai/work/code/LayoutLMV3_Fine_Tuning-main/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ai/work/code/LayoutLMV3_Fine_Tuning-main/venv/lib/python3.9/site-packages/transformers/models/layoutlmv3/modeling_layoutlmv3.py", line 343, in forward
    spatial_position_embeddings = self.calculate_spatial_position_embeddings(bbox)
  File "/home/ai/work/code/LayoutLMV3_Fine_Tuning-main/venv/lib/python3.9/site-packages/transformers/models/layoutlmv3/modeling_layoutlmv3.py", line 269, in calculate_spatial_position_embeddings
    raise IndexError("The `bbox` coordinate values should be within 0-1000 range.") from e
IndexError: The `bbox` coordinate values should be within 0-1000 range.

**Comment by manikanthp** [comment]
Hi Deepak,

The error you are getting because the bounding boxes values are not in the range. Make sure to trace back from inference.py file at line 54 as mentioned in above error  and It might be because the bboxes values that you are getting from PPstructure are not scaling down properly try to print from the point very you are passing as an image to ppstructure and check how the bboxes values are processing till we are passing it to encoder. I think I have also got the same issue but by tracking back  I have solved it but cannot recall what exactly I have changed it, If you got it please share it here.

if you issue is not resolved please update it here.


Thank you.

**Comment by manikanthp** [comment]
Hi Deepak,

In src folder -> trainer.py code try to give full path for the folder "layoutlmv3Microsoft" I have made this change in my local machine and not changed in git repo try this and check


![image](https://github.com/manikanthp/LayoutLMV3_Fine_Tuning/assets/27899776/e0cf9699-8983-427d-acdb-232343abc22c)
