### ISSUE TITLE
return nn.CrossEntropyLoss()(pred.view(-1,4),target.view(-1))

### ISSUE THREAD

**Issue by omachalin** [manikanthp/LayoutLMV3_Fine_Tuning#9]
I have 7 tags on the image. In Interface.py, I set up the model as follows:

`model = ModelModule(7)`

`class_1 = concat_torch[torch.where((concat_torch[:, 4] == 1) & (concat_torch[:, 3] == 0) & (concat_torch[:, 2] == 0))]
class_2 = concat_torch[torch.where((concat_torch[:, 4] == 2) & (concat_torch[:, 3] == 0) & (concat_torch[:, 2] == 0))]
class_3 = concat_torch[torch.where((concat_torch[:, 4] == 3) & (concat_torch[:, 3] == 0) & (concat_torch[:, 2] == 0))]
class_4 = concat_torch[torch.where((concat_torch[:, 4] == 4) & (concat_torch[:, 3] == 0) & (concat_torch[:, 2] == 0))]
class_5 = concat_torch[torch.where((concat_torch[:, 4] == 5) & (concat_torch[:, 3] == 0) & (concat_torch[:, 2] == 0))]
class_6 = concat_torch[torch.where((concat_torch[:, 4] == 6) & (concat_torch[:, 3] == 0) & (concat_torch[:, 2] == 0))]
class_7 = concat_torch[torch.where((concat_torch[:, 4] == 7) & (concat_torch[:, 3] == 0) & (concat_torch[:, 2] == 0))]

finl = torch.row_stack((class_1, class_2, class_3, class_4, class_5, class_6, class_7))`

I'm unsure whether to change the following function:
```
def loss_fn(pred, target):
    return nn.CrossEntropyLoss()(pred.view(-1, 4), target.view(-1))
```

I tried both view(-1, 4) and view(-1, 7). When I run the code, I encounter the following error:

```
Traceback (most recent call last):
  File "/opt/tg_screen/server/paddleOCR/src/Inference.py", line 51, in <module>
    op = model(input_ids=inputs_ids.unsqueeze(0),
  File "/opt/tg_screen/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/tg_screen/server/paddleOCR/src/trainer.py", line 33, in forward
    loss = loss_fn(output, lables)
  File "/opt/tg_screen/server/paddleOCR/src/trainer.py", line 12, in loss_fn
    return nn.CrossEntropyLoss()(pred.view(-1, 7), target.view(-1))
AttributeError: 'NoneType' object has no attribute 'view'
```

Thank you!

**Comment by Zw96042** [comment]
Probably doesn't help you now, but I'll post the solution so others can see. Basically when inferencing all you need to do is comment out the loss variable along with the return like shown below in the trainer.py file.
<img width="1688" height="504" alt="Image" src="https://github.com/user-attachments/assets/8aa0c98a-8b7e-4896-ab0a-68be2fe10c50" />
